# shivu/modules/storage.py

# Stores temporary character IDs generated via /dgen
generated_characters = {}

# Stores updated user balances (overwrites DB balance if present)
user_balances = {}

# Stores redeem codes generated by /gen or /dgen
generated_codes = {}

# Keeps track of codes that have been used already
used_codes = set()

# Keeps timestamps of /gen usage for cooldowns (24h limit and 5h gap logic)
cooldowns = {}

# Track last sell command time per user to prevent spamming
last_sell_time = {}
